### ISSUE TITLE
Jasmine-Ajax with Node.js + CommonJS says getJasmineRequireObj undefined

### ISSUE THREAD

**Issue by danascheider** [jasmine/jasmine-ajax#95]
I am testing the front end of a Backbone.js app using Node.js command line tools and CommonJS module loading. I used NPM to install Jasmine per the documentation and `jasmine init` to set up my project. Whenever I try to require Jasmine-Ajax, I get this exception:
<pre><code>/home/dana/Development/sandbox/node_modules/jasmine-ajax/lib/mock-ajax.js:33
getJasmineRequireObj().ajax = function(jRequire) {
^
ReferenceError: getJasmineRequireObj is not defined
    at Object.<anonymous> (/home/dana/Development/sandbox/node_modules/jasmine-ajax/lib/mock-ajax.js:33:1)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/dana/Development/sandbox/spec/protectedResourceSpec.js:3:1)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)</code></pre>
Something I read suggested this problem could be avoided by simply including `mock-ajax.js` in my Jasmine helpers directory, but when I did that, I repeatedly got errors like this:
<pre><code>Failures:
1) Protected Resource returns its token
  Message:
    TypeError: Cannot read property 'install' of undefined
  Stack:
    TypeError: Cannot read property 'install' of undefined
        at Object.<anonymous> (/home/dana/Development/sandbox/spec/protectedResourceSpec.js:14:17)
  Message:
    TypeError: Cannot read property 'token' of undefined
  Stack:
    TypeError: Cannot read property 'token' of undefined
        at Object.<anonymous> (/home/dana/Development/sandbox/spec/protectedResourceSpec.js:27:20)</code></pre>
(`token` is a property of my model.)

Am I correct in concluding that this plugin cannot be used in the Node environment/with CommonJS? (I am using `jsdom` for the `window` context.) If not, I'd be very grateful for any suggestions you have.

**Comment by slackersoft** [comment]
jasmine-ajax is definitely not designed with use outside of a browser in mind. It works by actually replacing the `XmlHttpRequest` constructor function on window with a mock. We think it should work in a CommonJS browser setup, but I haven't really tested it extensively there.

**Comment by kangax** [comment]
I just spent an hour trying to figure out why `require('jasmine-ajax')` doesn't work. It's defintely not obvious that jasmine-ajax is only meant for browser environment (it's cool but I wish I knew it before and go with something like SinonJS). A mention in the docs would save the time for other people.

**Comment by slackersoft** [comment]
I think I misunderstood the setup before. Theoretically, jasmine-ajax should work as long as there is an `XmlHTTPRequest` on `global` or `window` that we can replace.

The error with `getJasmineRequireObj` should probably be fixed by `require('jasmine-core')` before it to load all of the jasmine library onto the global. Unfortunately, I haven't really worked in this kind of setup, so I'm not sure what we would need to do to get it working.

I would be happy to review a pull request that addresses either:

1. documentation that you need to require something first for everything to work in this environment
1. a code update that makes this work without breaking non-CommonJS environments

**Comment by simongfxu** [comment]
Hope this would be settled down.

**Comment by simongfxu** [comment]
#137

**Comment by rafaellyra** [comment]
I added `require('jasmine-core')` and still not finding the global `getJasmineRequireObj `

**Comment by simongfxu** [comment]
@rafaellyra 
You need to modify the source code, because it did not pass the right global object.
See my PR https://github.com/jasmine/jasmine-ajax/pull/137
